---
title: Social Media Planner
timezone: UTC
email: your-email@example.com
description: A curated collection of ideas for your next social media post.
baseurl: '/cdv4'
url: 'http://davidpots/cdv4/'
twitter_username: posty_sike
github_username: posty_sike
plugins:
- jekyll-feed
google_analytics: false
